### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by madalienist** [prrvchr/SQLiteOOo#2]
I am trying to install this on a Macbook running Sonoma 14.6.1.  I  was able to install jdbcDriverOOo. I checked to make certain Java was updated.  I also checked that the latest version of Python was installed.  

I got the following error:

`(com.sun.star.uno.RuntimeException) { { Message = "<class 'ImportError'>: cannot import name 'g_path' from 'sqlite.configuration' (/Users/jeffkline/Library/Application Support/LibreOffice/4/user/uno_packages/cache/uno_packages/lu1491388rkl7.tmp_/SQLiteOOo.oxt/service/pythonpath/sqlite/configuration.py) (or 'documenthandler.DocumentHandler' is unknown), traceback follows\X000a  File \"/Applications/LibreOffice.app/Contents/Resources/pythonloader.py\", line 147, in writeRegistryInfo\X000a    mod = self.getModuleFromUrl( locationUrl )\X000a  File \"/Applications/LibreOffice.app/Contents/Resources/pythonloader.py\", line 102, in getModuleFromUrl\X000a    exec(codeobject, mod.__dict__)\X000a  File \"/Users/jeffkline/Library/Application Support/LibreOffice/4/user/uno_packages/cache/uno_packages/lu1491388rkl7.tmp_/SQLiteOOo.oxt/service/OptionsHandler.py\", line 37, in <module>\X000a    from sqlite import OptionsManager\X000a  File \"/Applications/LibreOffice.app/Contents/Resources/uno.py\", line 346, in _uno_import\X000a    return _builtin_import(name, *optargs, **kwargs)\X000a  File \"/Users/jeffkline/Library/Application Support/LibreOffice/4/user/uno_packages/cache/uno_packages/lu1491388rkl7.tmp_/SQLiteOOo.oxt/service/pythonpath/sqlite/__init__.py\", line 30, in <module>\X000a    from . import sdbc\X000a  File \"/Applications/LibreOffice.app/Contents/Resources/uno.py\", line 346, in _uno_import\X000a    return _builtin_import(name, *optargs, **kwargs)\X000a  File \"/Users/jeffkline/Library/Application Support/LibreOffice/4/user/uno_packages/cache/uno_packages/lu1491388rkl7.tmp_/SQLiteOOo.oxt/service/pythonpath/sqlite/sdbc/__init__.py\", line 30, in <module>\X000a    from .driver import Driver\X000a  File \"/Applications/LibreOffice.app/Contents/Resources/uno.py\", line 346, in _uno_import\X000a    return _builtin_import(name, *optargs, **kwargs)\X000a  File \"/Users/jeffkline/Library/Application Support/LibreOffice/4/user/uno_packages/cache/uno_packages/lu1491388rkl7.tmp_/SQLiteOOo.oxt/service/pythonpath/sqlite/sdbc/driver.py\", line 33, in <module>\X000a    from ..driver import Driver as DriverBase\X000a  File \"/Applications/LibreOffice.app/Contents/Resources/uno.py\", line 346, in _uno_import\X000a    return _builtin_import(name, *optargs, **kwargs)\X000a  File \"/Users/jeffkline/Library/Application Support/LibreOffice/4/user/uno_packages/cache/uno_packages/lu1491388rkl7.tmp_/SQLiteOOo.oxt/service/pythonpath/sqlite/driver.py\", line 41, in <module>\X000a    from .documenthandler import DocumentHandler\X000a  File \"/Applications/LibreOffice.app/Contents/Resources/uno.py\", line 425, in _uno_import\X000a    raise uno_import_exc\X000a  File \"/Applications/LibreOffice.app/Contents/Resources/uno.py\", line 346, in _uno_import\X000a    return _builtin_import(name, *optargs, **kwargs)\X000a  File \"/Users/jeffkline/Library/Application Support/LibreOffice/4/user/uno_packages/cache/uno_packages/lu1491388rkl7.tmp_/SQLiteOOo.oxt/service/pythonpath/sqlite/documenthandler.py\", line 57, in <module>\X000a    from .configuration import g_path\X000a\X000a at /Users/cloph/build/workdir/UnoApiHeadersTarget/udkapi/normal/com/sun/star/uno/RuntimeException.hdl:24", Context = (com.sun.star.uno.XInterface) @0 } }`

**Comment by prrvchr** [comment]
Hi madalienist,

This is unfortunately normal, a regression has slipped into the code with the publication of the JaybirdOOo extension.
Thank you for reporting this malfunction to me.

I have just published version 1.2.2 which should fix this problem and also others...

I'll let you try and close this issue if everything is back to normal.
